name: Terraform Checks

on:
  pull_request:
    branches:
      - main
    paths:
      - '*.tf'
      - 'python/*.py'
      - README.md
      #      - 'terraform/*'

jobs:
  Terraform-Checks:
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt check
      id: fmt
      run: terraform fmt -check

    - name: Terraform init
      run: terraform init -backend=false

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: latest
    
    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact